---

- name: 6.1 Ensure the X Window system is not installed (Scored)
  apt: name="xserver-xorg-core*" state=absent

- name: 6.2 Ensure Avahi Server is not enabled (Scored)
  lineinfile: dest={{ item }} regexp="^start on" state=absent
  with_items:
    - /etc/init/avahi-daemon.conf

- name: 6.3 Ensure print server is not enabled (Not Scored)
  lineinfile: dest={{ item }} regexp="^start on" state=absent
  with_items:
    - /etc/init/avahi-daemon.conf

- name: 6.4 Ensure DHCP Server is not enabled (Scored)
  lineinfile: dest={{ item }} regexp="^start on" state=absent
  with_items:
    - /etc/init/isc-dhcp-server.conf
    - /etc/init/isc-dhcp-server6.conf

- name: 6.5 Configure Network Time Protocol (NTP) (Scored)
  apt: name=ntp

- name: 6.5 Configure Network Time Protocol (NTP) (Scored)
  lineinfile: dest=/etc/ntp.conf regexp={{ item }} line={{ item }}
  with_items:
    - "restrict -4 default kod nomodify notrap nopeer noquery"
    - "restrict -6 default kod nomodify notrap nopeer noquery"

- name: 6.6 Ensure LDAP is not enabled (Not Scored)
  apt: name=slapd state=absent

- name: 6.7 Ensure NFS and RPC are not enabled (Not Scored)
  lineinfile: dest={{ item }} regexp="^start on" state=absent
  with_items:
    - /etc/init/rpcbind-boot.conf

- name: 6.7 Ensure NFS and RPC are not enabled (Not Scored)
  file: path="/etc/rc*.d/S*nfs-kernel-server" state=absent

- name: 6.8 Ensure DNS Server is not enabled (Not Scored)
  file: path="/etc/rc*.d/S*bind9" state=absent

- name: 6.9 Ensure FTP Server is not enabled (Not Scored)
  lineinfile: dest={{ item }} regexp="^start on" state=absent
  with_items:
    - /etc/init/vsftpd.conf

- name: 6.10 Ensure HTTP Server is not enabled (Not Scored)
  file: path="/etc/rc*.d/S*apache2" state=absent

- name: 6.11 Ensure IMAP and POP server is not enabled (Not Scored)
  lineinfile: dest={{ item }} regexp="^start on" state=absent
  with_items:
    - /etc/init/dovecot.conf

- name: 6.12 Ensure Samba is not enabled (Not Scored)
  lineinfile: dest={{ item }} regexp="^start on" state=absent
  with_items:
    - /etc/init/smbd.conf

- name: 6.13 Ensure HTTP Proxy Server is not enabled (Not Scored)
  lineinfile: dest={{ item }} regexp="^start on" state=absent
  with_items:
    - /etc/init/squid3.conf

- name: 6.14 Ensure SNMP Server is not enabled (Not Scored)
  file: path="/etc/rc*.d/S*snmpd" state=absent

- name: 6.15 Configure Mail Transfer Agent for Local-Only Mode (Scored)
  lineinfile: dest=/etc/postfix/main.cf regexp="^inet_interfaces" line="inet_interfaces = localhost"

- name: 6.16 Ensure rsync service is not enabled (Scored)
  lineinfile: dest=/etc/default/rsync regexp="RSYNC_ENABLE" line="RSYNC_ENABLE=false"

- name: 6.17 Ensure Biosdevname is not enabled (Scored)
  apt: name=biosdevname state=absent
