---

- name: 10.1.1 Set Password Expiration Days (Scored)
  lineinfile: path=/etc/login.defs regexp='PASS_MAX_DAYS' line='PASS_MAX_DAYS 90'

- name: 10.1.2 Set Password Change Minimum Number of Days (Scored)
  lineinfile: path=/etc/login.defs regexp='PASS_MIN_DAYS' line='PASS_MIN_DAYS 7'

- name: 10.1.3 Set Password Expiring Warning Days (Scored)
  lineinfile: path=/etc/login.defs regexp='PASS_WARN_AGE' line='PASS_WARN_AGE 7'

- name: 10.2 Disable System Accounts (Scored)
  debug: msg='Verify that the shell field for system accounts is set to /usr/sbin/nologin'

- name: 10.3 Set Default Group for root Account (Scored)
  user: name=root group=root

- name: 10.4 Set Default umask for Users (Scored)
  lineinfile: path=/etc/login.defs regexp='^UMASK' line='UMASK 077'

- name: 10.5 Lock Inactive User Accounts (Scored)
  debug: msg='useradd -D -f 35'
