---

- name: 5.1.1, 5.1.3, 5.1.5 Ensure NIS, rsh client, talk client are not installed (Scored)
  apt: name={{ item }} state=absent
  with_items:
    - nis
    - rsh-client
    - rsh-reload-client
    - talk

- name: 5.1.2, 5.1.4, 5.1.6 - 5.1.7, 5.2, 5.3, 5.4, 5.5, 5.6 Ensure rsh server, talk server, telnet server, tftp-server, chargen, daytime, echo, discard, time are not enabled (Scored)
  lineinfile: dest=/etc/inetd.conf regexp="^{{ item }}" state=absent
  with_items:
    - shell
    - login
    - exec
    - talk
    - ntalk
    - telnet
    - tftp
    - chargen
    - daytime
    - echo
    - discard
    - time

- name: 5.1.8 Ensure xinetd is not enabled (Scored)
  lineinfile: dest=/etc/init/xinetd.conf regexp="start on runlevel" state-absent
