---

- name: 2.1 Create Separate Partition for /tmp (Scored)
  debug: msg="*** Manually create separate partition for /tmp."

- name: 2.2 - 2.4 Set nodev,nosuid,noexec option for /tmp Partition (Scored)
  mount: >
    name="/tmp"
    src={{ item.device }}
    state=mounted
    fstype={{ item.fstype }}
    opts="nodev,nosuid,noexec"
  when: item.mount == "/tmp"
  with_items: ansible_mounts

- name: 2.5 Create Separate Partition for /var (Scored)
  debug: msg="*** Manually create separate partition for /var."

- name: 2.6 Bind Mount the /var/tmp directory to /tmp (Scored)
  mount: >
    name="/var/tmp"
    src="/tmp"
    state=mounted
    fstype="none"
    opts="bind"
  when: item.mount == "/tmp"
  with_items: ansible_mounts
    
- name: 2.7 Create Separate Partition for /var/log (Scored)
  debug: msg="*** Manually create separate partition for /var/log."

- name: 2.8 Create Separate Partition for /var/log/audit (Scored)
  debug: msg="*** Manually create separate partition for /var/log/audit."

- name: 2.9 Create Separate Partition for /home (Scored)
  debug: msg="*** Manually create separate partition for home."

- name: 2.10 Add nodev Option to /home (Scored)
  mount: >
    name="/home"
    src={{ item.device }}
    state=mounted
    fstype={{ item.fstype }}
    opts="nodev"
  when: item.mount == "/home"
  with_items: ansible_mounts

- name: 2.11 - 2.13 Add nodev,noexec,nosuid Options to Removable Media Partitions (Not Scored)
  debug: msg="*** Manually add nodev,noexec,nosuid options to removable media partitions."

- name: 2.14 - 2.16 Add nodev,noexec,nosuid Options to /run/shm Partition (Scored)
  debug: msg="*** Manually add nodev,noexec,nosuid options to removable media partitions."

- name: 2.17 Set Sticky Bit on All World-Writable Directories (Scored)
  shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d -perm -0002 2>/dev/null | xargs chmod a+t

- name: 2.25 Disable Automounting (Scored)
  lineinfile: dest=/etc/init/autofs.conf regexp='start on runlevel' state=absent
