---

- name: 7.1.1 Disable IP Forwarding (Scored)
  sysctl: name={{ item }} value=0
  with_items:
    - net.ipv4.ip_forward

- name: 7.1.2 Disable Send Packet Redirects (Scored)
  sysctl: name={{ item }} value=0
  with_items:
    - net.ipv4.conf.all.send_redirects
    - net.ipv4.conf.default.send_redirects

- name: 7.2.1 Disable Source Routed Packet Acceptance (Scored)
  sysctl: name={{ item }} value=0
  with_items:
    - net.ipv4.conf.all.accept_source_route
    - net.ipv4.conf.default.accept_source_route

- name: 7.2.2 Disable ICMP Redirect Acceptance (Scored)
  sysctl: name={{ item }} value=0
  with_items:
    - net.ipv4.conf.all.accept_redirects
    - net.ipv4.conf.default.accept_redirects

- name: 7.2.3 Disable Secure ICMP Redirect Acceptance (Scored)
  sysctl: name={{ item }} value=0
  with_items:
    - net.ipv4.conf.all.secure_redirects
    - net.ipv4.conf.default.secure_redirects

- name: 7.2.4 Log Suspicious Packets (Scored)
  sysctl: name={{ item }} value=1
  with_items:
    - net.ipv4.conf.all.log_martians
    - net.ipv4.conf.default.log_martians

- name: 7.2.5 Enable Ignore Broadcast Requests (Scored)
  sysctl: name={{ item }} value=1
  with_items:
    - net.ipv4.icmp_echo_ignore_broadcasts 

- name: 7.2.6 Enable Bad Error Message Protection (Scored)
  sysctl: name={{ item }} value=1
  with_items:
    - net.ipv4.icmp_ignore_bogus_error_responses

- name: 7.2.7 Enable RFC-recommended Source Route Validation (Scored)
  sysctl: name={{ item }} value=1
  with_items:
    - net.ipv4.conf.all.rp_filter
    - net.ipv4.conf.default.rp_filter

- name: 7.2.8 Enable TCP SYN Cookies (Scored)
  sysctl: name={{ item }} value=1
  with_items:
    - net.ipv4.tcp_syncookies

- name: 7.3.1 Disable IPv6 Router Advertisements (Not Scored)
  sysctl: name={{ item }} value=0
  with_items:
    - net.ipv6.conf.all.accept_ra
    - net.ipv6.conf.default.accept_ra

- name: 7.3.2 Disable IPv6 Redirect Acceptance (Not Scored)
  sysctl: name={{ item }} value=0
  with_items:
    - net.ipv6.conf.all.accept_redirects
    - net.ipv6.conf.default.accept_redirects

- name: 7.3.3 Disable IPv6 (Not Scored)
  sysctl: name={{ item }} value=1
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: 7.4.1 Install TCP Wrappers (Scored)
  apt: name=tcpd

- name: 7.4.2 - 7.4.3 Create /etc/hosts.allow (Scored)
  file: path=/etc/hosts.allow owner=root group=root mode=644

- name: 7.4.4 - 7.4.5 Create /etc/hosts.deny (Scored)
  copy: path=/etc/hosts.deny owner=root group=root mode=644 content='ALL: ALL'

- name: 7.5.1 Disable DCCP (Not Scored)
  lineinfile: dest=/etc/modprobe.d/CIS.conf regexp='^install dccp /bin/true' line='install dccp /bin/true'

- name: 7.5.2 Disable SCTP (Not Scored)
  lineinfile: dest=/etc/modprobe.d/CIS.conf regexp='^install sctp /bin/true' line='install sctp /bin/true'

- name: 7.5.3 Disable RDS (Not Scored)
  lineinfile: dest=/etc/modprobe.d/CIS.conf regexp='^install rds /bin/true' line='install rds /bin/true'

- name: 7.5.4 Disable TIPC (Not Scored)
  lineinfile: dest=/etc/modprobe.d/CIS.conf regexp='^install tipc /bin/true' line='install tipc /bin/true'

- name: 7.6 Deactivate Wireless Interfaces (Not Scored)
  debug: msg='Use the following command to disable wireless: nmcli nm wifi off'

- name: 7.7 Ensure Firewall is active (Scored)
  ufw: state=enabled
