---

- name: 9.1.1 Enable cron Daemon (Scored)
  service: name=cron state=enabled

- name: 9.1.2 Set User/Group Owner and Permission on /etc/crontab (Scored)
  file: path=/etc/crontab owner=root group=root mode=0600

- name: 9.1.3 Set User/Group Owner and Permission on /etc/cron.hourly (Scored)
  file: path=/etc/cron.hourly owner=root group=root mode=0700

- name: 9.1.4 Set User/Group Owner and Permission on /etc/cron.daily (Scored)
  file: path=/etc/cron.daily owner=root group=root mode=0700

- name: 9.1.5 Set User/Group Owner and Permission on /etc/cron.weekly (Scored)
  file: path=/etc/cron.weekly owner=root group=root mode=0700

- name: 9.1.6 Set User/Group Owner and Permission on /etc/cron.monthly (Scored)
  file: path=/etc/cron.monthly owner=root group=root mode=0700

- name: 9.1.7 Set User/Group Owner and Permission on /etc/cron.d (Scored)
  file: path=/etc/cron.d owner=root group=root mode=0700

- name: 9.1.8 Restrict at/cron to Authorized Users (Scored)
  file: path=/etc/cron.allow owner=root group=root mode=0600 state=touch

- name: 9.1.8 Restrict at/cron to Authorized Users (Scored)
  file: path=/etc/at.allow owner=root group=root mode=0600 state=touch

- name: 9.2.1 Set Password Creation Requirement Parameters Using pam_cracklib (Scored)
  lineinfile: path=/etc/pam.d/common-password regexp='^password required pam_cracklib.so' line='password required pam_cracklib.so retry=3 minlen=14 dcredit=-1 ucredit=-1 ocredit=-1 lcredit=-1'

- name: 9.2.2 Set Lockout for Failed Password Attempts (Not Scored)
  lineinfile: path=/etc/pam.d/login regexp='^auth required pam_tally2.so' line='auth required pam_tally2.so onerr=fail audit silent deny=5 unlock_time=900'

- name: 9.2.3 Limit Password Reuse (Scored)
  lineinfile: path=/etc/pam.d/common-password regexp='remember' line='password sufficient pam_unix.so remember=5'

- name: 9.3.1 Set SSH Protocol to 2 (Scored)
  lineinfile: path=/etc/ssh/sshd_config regexp='^Protocol' line='Protocol 2'

- name: 9.3.2 Set LogLevel to INFO (Scored)
  lineinfile: path=/etc/ssh/sshd_config regexp='^LogLevel' line='LogLevel INFO'

- name: 9.3.3 Set Permissions on /etc/ssh/sshd_config (Scored)
  file: path=/etc/ssh/sshd_config owner=root group=root mode=0600

- name: 9.3.4 Disable SSH X11 Forwarding (Scored)
  lineinfile: path=/etc/ssh/sshd_config regexp='^X11Forwarding' line='X11Forwarding no'

- name: 9.3.5 Set SSH MaxAuthTries to 4 or Less (Scored)
  lineinfile: path=/etc/ssh/sshd_config regexp='^MaxAuthTries' line='MaxAuthTries 4'

- name: 9.3.6 Set SSH IgnoreRhosts to Yes (Scored)
  lineinfile: path=/etc/ssh/sshd_config regexp='^IgnoreRhosts' line='IgnoreRhosts yes'

- name: 9.3.7 Set SSH HostbasedAuthentication to No (Scored)
  lineinfile: path=/etc/ssh/sshd_config regexp='^HostbasedAuthentication' line='HostbasedAuthentication no'

- name: 9.3.8 Disable SSH Root Login (Scored)
  lineinfile: path=/etc/ssh/sshd_config regexp='^PermitRootLogin' line='PermitRootLogin no'

- name: 9.3.9 Set SSH PermitEmptyPasswords to No (Scored)
  lineinfile: path=/etc/ssh/sshd_config regexp='^PermitEmptyPasswords' line='PermitEmptyPasswords no'

- name: 9.3.10 Do Not Allow Users to Set Environment Options (Scored)
  lineinfile: path=/etc/ssh/sshd_config regexp='PermitUserEnvironment' line='PermitUserEnvironment no'

- name: 9.3.11 Use Only Approved Cipher in Counter Mode (Scored)
  lineinfile: path=/etc/ssh/sshd_config regexp='Ciphers' line='Ciphers aes128-ctr,aes192-ctr,aes256-ctr'

- name: 9.3.12 Set Idle Timeout Interval for User Login (Scored)
  lineinfile: path=/etc/ssh/sshd_config regexp='^ClientAliveInterval' line='ClientAliveInterval 300'

- name: 9.3.12 Set Idle Timeout Interval for User Login (Scored)
  lineinfile: path=/etc/ssh/sshd_config regexp='^ClientAliveCountMax' line='ClientAliveCountMax 0'

- name: 9.3.13 Limit Access via SSH (Scored)
  debug: msg='Set one or more of AllowUsers, AllowGroups, DenyUsers, and DenyGroups in /etc/ssh/sshd_config'

- name: 9.3.14 Set SSH Banner (Scored)
  lineinfile: path=/etc/ssh/sshd_config regexp='^Banner' line='Banner /etc/issue.net'

- name: 9.4 Restrict root Login to System Console (Not Scored)
  debug: msg='Remove entries for any consoles that are not in a physically secure location.'

- name: 9.5 Restrict Access to the su Command (Scored)
  lineinfile: path=/etc/pam.d/su regexp='^auth required pam_wheel.so use_uid' line='auth required pam_wheel.so use_uid'
